### ISSUE TITLE
Filter secure information from Plug.Conn

### ISSUE THREAD

**Issue by dbhobbs** [appsignal/appsignal-elixir#182]
While evaluating AppSignal at my work I noticed that there are some secrets that are being leaked when a Plug.Conn is dumped. I'm specifically looking at the `secret_key_base` that Phoenix uses for token generation, though I can see other keys being added to the connection in an endpoint that should probably not be dumped.

Is there a way to filter those values out? Or could a filter be added to the instrumentation configuration similar to Phoenix's `filter_parameters`?

**Comment by jeffkreeftmeijer** [comment]
Hey @dbhobbs, thanks for reporting this issue.

We're currently sending the full `System.stacktrace` when an error occurs, which includes the arguments passed to the function that caused the error. That's really useful most of the time (because it allows you to see which function clause was called, or which set of arguments causes a FunctionClauseError). 

For a `%Plug.Conn{}`, we should make an exception to filter out sensitive data, like the `secret_key_base`. We'll make sure that's fixed in a future release. Thanks!
