### ISSUE TITLE
Use hackney for downloading extension and diagnostics

### ISSUE THREAD

**Issue by joshuataylor** [appsignal/appsignal-elixir#238]
Solution 1:

```
  defp download_file(url, version) do
    filename = Path.join(tmp_dir(), "appsignal-agent-#{version}.tar.gz")
    case File.exists?(filename) do
      true ->
        filename
      false ->
        Application.ensure_all_started(:inets)

        Logger.info "Downloading agent release from #{url}"
        {:ok, resp} = :httpc.request(:get, {url, []}, [], [body_format: :binary])
        {{_, 200, 'OK'}, _headers, body} = resp

        File.write!(filename, body)
    end
  end
```

Solution #2: Just use HTTPoison, which is included in the `mix.exs` already.

**Comment by tombruijn** [comment]
Hi @joshuataylor,

The package is using curl right now to download our agent package as it is a tool that's present on most systems.

It's not ideal. We do want to drop the curl and HTTPoison dependency eventually.

Already we've briefly looked at using httpc in PR #140, but due to some issues with SSL verification we decided to focus on other things right now.

We will come back to this issue and try to drop both the curl and HTTPoison dependency.

**Comment by tombruijn** [comment]
Keeping issue open as a reminder that dropping curl and HTTPoison is a project to look at for v1.4.

**Comment by jeffkreeftmeijer** [comment]
Reopening this, as #344 doesn't fix this issue. It's a first step in the right direction, but we still need to switch from cURL to Hackney to download the agent.
