### ISSUE TITLE
GenServer instrumentation (helper)

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-elixir#252]
Provide an easy one-two line solution to instrumenting GenServers.

For example by (only) including a module:

```elixir
defmodule Foo do
  use GenServer
  use Appsignal.Instrumentation.GenServer

  # GenServer implementation
end
```

## Requested

As [reported here](https://app.intercom.io/a/apps/yzor8gyw/respond/inbox/540709/conversations/11564958544) (private link)

## Timebox

1 day to see if it can work as a instrumentation we ship in our integration.

**Comment by achempion** [comment]
Yes, would be definitely nice to have

**Comment by tombruijn** [comment]
Let's get back to it if someone asks for it again. Closing for now.

**Comment by unflxw** [comment]
@1player Pretty timely answer on your end! We closed this because we were unsure if there was enough interest in it -- we can reconsider this decision.

Part of the reason we closed this is that we are unsure of what a good GenServer instrumentaton would look like. Would you be interested in trying out a proof of concept for it and giving us feedback? If so, please reach out to us at support@appsignal.com, and mention this issue on your message.
