### ISSUE TITLE
Building with docker can prevent appsignal from downloading proper archive

### ISSUE THREAD

**Issue by ankhers** [appsignal/appsignal-elixir#254]
#### Setup

I am running MacOS. I am using docker to build my application for deployment.

#### Replication Instructions

If I run 

```
mix deps.get
mix deps.compile
```

on my MacOS machine, it will download and compile everything appsignal needs which works perfectly. If I then attempt to do the same within a Dockerfile

```
FROM elixir:1.5.1

RUN apt-get clean && apt-get update -qq && apt-get -y install build-essential curl

COPY ./ /app

WORKDIR /app

RUN mix local.hex --force
RUN mix local.rebar --force
RUN mix deps.get
RUN mix deps.compile
```

I will get a compilation error as follows.

```
/app/_build/prod/lib/appsignal/priv/libappsignal.a: member /app/_build/prod/lib/appsignal/priv/libappsignal.a(__.SYMDEF) in archive is not an object
collect2: error: ld returned 1 exit status
make: *** [all] Error 1
Makefile:22: recipe for target 'all' failed
==> appsignal
could not compile dependency :appsignal, "mix compile" failed. You can recompile this dependency with "mix deps.compile appsignal", update it with "mix deps.update appsignal" or clean it with "mix deps.clean appsignal"
** (Mix) Could not run `make`. Please check if `make` and either `clang` or `gcc` are installed
```

It appears as though the compilation scripts have found that there is already an archive (in this case, of the incorrect architecture) and will not download a new one for the proper architecture. Or maybe it gets unpacked into an architecture agnostic directory?

#### Workaround

You can add `RUN mix deps.clean appsignal` before the `RUN mix deps.get` line and it will work.

You could also create a `.dockerignore` file and add `deps` and `_build` to it.

**Comment by tombruijn** [comment]
Thanks for creating the report! ([related Intercom thread](https://app.intercom.io/a/apps/yzor8gyw/respond/inbox/540709/conversations/11672121760))

Checking if the architecture is the same is probably something we should do :)

**Comment by teamon** [comment]
@ankhers did you put _build (and deps) in .dockerignore?

**Comment by jschorr** [comment]
+1 I get the same result.

**Comment by EskiMag** [comment]
Same here. What's the suggested approach to this Docker cross-compilation releases?

**Comment by tombruijn** [comment]
For now, using .dockerignore to ignore the AppSignal package and compiling the dependency on the container as well.

We want to fix this in our package as well by comparing the current architecture against the cached extension files, and when they don't match redo the installation. We're only now able to do this properly since #433. But may want to switch to Jason first in #474 as we'll need to read the JSON install report in the installation step.

**Comment by tombruijn** [comment]
Let's revisit this, we say this happening here again as well: https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700076724

**Comment by teamon** [comment]
I got bit by this again. 

In case you have have a similar situation - downloading dependencies from private hex registries (e.g. oban_web or oban_pro) outside of docker and then `COPY`-ing them into the container the trick is to force recompile appsignal package afterwards:

```Dockerfile
COPY deps deps
RUN mix deps.compile
RUN mix deps.compile appsignal --force
```

This will force appsignal to download correct binary for the current OS (in my case Alpine+musl) instead of the host machine (local macOS or Ubuntu CI).

**Comment by tombruijn** [comment]
After looking into this for our Node.js integration ([related Node.js issue comment](https://github.com/appsignal/appsignal-nodejs/issues/658#issuecomment-1149816515)) I also had a look at our Elixir integration.
The same problem is present here too. As noticed in earlier comments in this issue, only running `mix compile` on the container will not work. Our mix helper that installs the extension is not called on `mix compile`. One needs to explicitly run `mix deps.compile appsignal [--force]`. We can improve the error message to give this hint to the user whenever this happens.
