### ISSUE TITLE
🐞 Instrumentation leaks process monitors

### ISSUE THREAD

**Issue by lukaszsamson** [appsignal/appsignal-elixir#299]
Environment: Linux, Elixir 1.5.3, Erlang 20.2, AppSignal 1.4.5 (prod)
macOS, Elixir 1.6.0, Erlang 20.2, AppSignal 1.4.7 (dev)

Adding instrumentation to long running processes results in memory leak through process monitor leak. Every execution of instrumented function leads to one leaked `MonitorRef` added by `Elixir.Appsignal.TransactionRegistry` process. As a result process memory of both `Appsignal.TransactionRegistry` and the long running process increases with every execution. On our production environment it amounts to ~120MB leak per 4M transactions and eventually VM crash due to OOM error.
The issue affects both manual and decorator based instrumentation as shown below.

Repro steps:
1. Add the following `GenServer` to app with instrumentation
```
defmodule MyApp.LeakingServer do
  use GenServer
  use Appsignal.Instrumentation.Decorators
  import Appsignal.Instrumentation.Helpers, only: [instrument: 4]

  def start_link() do
    GenServer.start_link(__MODULE__, :ok, name: __MODULE__)
  end

  def init(:ok) do
    1..100 |> Enum.map(fn _ -> test_decorator() end)
    1..100 |> Enum.map(fn _ -> test_wrapper() end)

    {:ok, :ok}
  end

  @decorate transaction(:background_job)
  def test_decorator() do
    IO.puts "test"
  end

  def test_wrapper() do
    transaction = Appsignal.Transaction.start(
      Appsignal.Transaction.generate_id,
      : background_job
    )
    instrument(transaction, "complex.function", "Rendering something slow", fn() ->
        IO.puts "test"
    end)
    Appsignal.Transaction.finish(transaction)
    :ok = Appsignal.Transaction.complete(transaction)
  end
end
```
2. Run the app
3. Check monitors on `MyApp.LeakingServer` process (e.g. in observer)

Optional steps:
4. Increase number of transactions to e.g. 10k
5. Observe growing process memory

Result: `Appsignal.TransactionRegistry` monitors `MyApp.LeakingServer` 200 times
Expected result: `Appsignal.TransactionRegistry` calls [:erlang.demonitor](http://erlang.org/doc/man/erlang.html#demonitor-1) when transaction completes

**Comment by thijsc** [comment]
Thanks for the thorough report, we're going to reproduce this and will reply here.

**Comment by jeffkreeftmeijer** [comment]
Hey @lukaszsamson, thanks for the great report!

We've looked into this and found that we're indeed leaking monitors if the process continues to exist after the transaction has been finished. In that case, the monitor doesn't get removed because the monitored process doesn't go DOWN. Besides that, the transaction doesn't get removed from ets.

This is caused by the way the `Appsignal.TransactionRegistry` is set up. It assumes that each Transaction that's started has a unique PID (which is what happens for requests in a Phoenix app, for example). Whenever a Transaction is started, it's stored in ets using its PID, and a monitor is created, so the registry is notified when the Transaction's process goes DOWN.

When the registry receives a DOWN message through one of its monitors, it [removes](https://github.com/appsignal/appsignal-elixir/blob/master/lib/appsignal/transaction/registry.ex#L107-L116) all Transactions that match the monitored process' PID, and each monitor for that process is cleaned up automatically.

This means that running multiple Transactions from one process results in leaving multiple monitors, and multiple records in the ets table right now.

To fix this, we should move off the assumption that each Transaction has a unique PID. We'll have to look into how we'd do this, but it looks like we'd be more flexible using the monitor reference instead of PIDs as keys in ets to support something like this without leaking monitors and ets rows. 🤔
