### ISSUE TITLE
priv is missing, no failure during compile

### ISSUE THREAD

**Issue by schnittchen** [appsignal/appsignal-elixir#301]
Hello,

After upgrading to elixir 1.6.0, my app lost appsignal monitoring. I dug in and found out that `_build/prod/lib/appsignal/priv/` was missing, and with it the agent.

The `mix deps.update decorator` workaround mentioned in https://github.com/appsignal/appsignal-elixir/issues/268 does not help.

Here's how I can reproduce the issue:
```
> mix deps.compile # pretends to be fine (no error), but _build/prod/lib/appsignal/priv/ missing
> mix deps.compile # yes, again! => _build/prod/lib/appsignal/priv/ present

**Comment by schnittchen** [comment]
I've duplicated the
```
RUN MIX_ENV=$MIX_ENV gosu my_user mix deps.compile
```
line in my Dockerfile and now it works. Interestingly, there's no trace of appsignal compiling in the second `mix deps.compile` step:

```
Step 20/44 : RUN MIX_ENV=$MIX_ENV gosu my_user mix deps.compile
 ---> Running in 89752b6df707
===> Compiling mimerl
===> Compiling metrics
===> Compiling unicode_util_compat
===> Compiling idna
===> Compiling ranch
==> poolboy (compile)
warning: variable "package" does not exist and is being expanded to "package()", please use parentheses to remove the ambiguity or change the variable name
  /app/deps/decimal_arithmetic/mix.exs:10

warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  /app/deps/decimal_arithmetic/mix.exs:12

warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  /app/deps/parallel_stream/mix.exs:9

warning: variable "package" does not exist and is being expanded to "package()", please use parentheses to remove the ambiguity or change the variable name
  /app/deps/parallel_stream/mix.exs:10

warning: String.strip/1 is deprecated, use String.trim/1
  /app/deps/poison/mix.exs:4

==> ssl_verify_fun (compile)
==> bcrypt_elixir
make: Nothing to be done for 'all'.
===> Compiling certifi
===> Compiling hackney
==> cowlib (compile)
==> cowboy (compile)
Compiled src/cowboy_protocol.erl
 ---> 1110e1dee54c
Removing intermediate container 89752b6df707
```

**Comment by jeffkreeftmeijer** [comment]
Hey @schnittchen,

I've done some testing, but wasn't able to reproduce your problem yet. Does it work when you remove the `_build` directory and run `MIX_ENV=prod mix deps.compile`? It sounds like the dependency was compiled for the dev environment instead of the prod one, because `MIX_ENV` wasn't set in your first example, and it defaulted to the dev env. Could that be it?

**Comment by schnittchen** [comment]
I'm currently experiencing the same phenomenon in the dev environment alone.

Any idea what I could try to find out what might be triggering this?

**Comment by jeffkreeftmeijer** [comment]
Hey @schnittchen,

We're trying to reproduce what's happening here. For us, removing the _build directory and compiling the dependencies using `mix deps.compile` works on the first try on Elixir 1.6.

Could you paste the Dockerfile this is failing on? You said this is also happening in the dev environment, does that mean it's failing on your own machine as well?

**Comment by schnittchen** [comment]
I finally found the time to dig deeper here. I raised an exception right below https://github.com/appsignal/appsignal-elixir/blob/develop/mix_helpers.exs?utf8=%E2%9C%93#L42

Running `mix deps.compile appsignal` once, and `/app/_build/dev/lib/appsignal/priv` did not exist, running it again and afterwards the directory had been created. I inspected the output of `priv_dir` on the line above:

First time: "/app/_build/dev/lib/appsignal/.mix/priv"
Second time: "/app/_build/dev/lib/appsignal/priv"

**Comment by schnittchen** [comment]
This might be interesting:

```
iex(8)> Mix.Project.in_project(:appsignal, "/", fn _ -> Mix.Project.manifest_path end)
"/_build/dev/lib/appsignal/.mix"
```

together with this snippet of documentation: https://github.com/elixir-lang/elixir/blob/v1.6/lib/mix/lib/mix/project.ex#L442
(My app is inside an umbrella!) Also note this commit for Elixir 1.6.0: https://github.com/elixir-lang/elixir/commit/d941fe0d8cfb7d489c685c8e315a2305742e6191

**Comment by jeffkreeftmeijer** [comment]
Hey @schnittchen,

Thanks for the extra information. I've been trying to reproduce this issue in my [umbrella example app](https://github.com/jeffkreeftmeijer/appsignal-umbrella-example), but still haven't been able to. We find the priv_path [here](https://github.com/appsignal/appsignal-elixir/blob/master/lib/appsignal/system.ex#L15-L26), which has a fallback to use when the app signal dependency wasn't compiled yet. This had a problem 1.6, but we pushed a fix for that in https://github.com/appsignal/appsignal-elixir/commit/3e5e924e032c0549cd711b7de3f1b798fb33d507, as 1.4.7. 

You seem to be running the current master, as you've made changes, but to be 100% sure; you're running a version above 1.4.7, right? If you are, this might be something caused by your setup. Could you post your Dockerfile, so we can do some testing on that? Also, could you try the umbrella app to see if that compiles on the first try?

**Comment by schnittchen** [comment]
I'll dig deeper as soon as I find the time.

**Comment by schnittchen** [comment]
My apologies. I was still running 1.4.5, but assumed 1.4.6. Everything looks fine now on 1.4.9!

**Comment by tombruijn** [comment]
That's great to hear @schnittchen !
