### ISSUE TITLE
Disable appsignal printout in tests

### ISSUE THREAD

**Issue by axelson** [appsignal/appsignal-elixir#335]
I already have this in my `config/test.exs` (and it is being loaded in the test environment)

```
config :appsignal, :config,
  active: false
```

Yet I still have this line showing up in my test output when running `mix test`

    09:36:56.086 [warn]  Warning: No valid AppSignal configuration found, continuing with AppSignal metrics disabled.

Is there anything I can do to suppress that line?

**Comment by tombruijn** [comment]
Hi @axelson,

What test library are you using? We have a [suppression for ExUnit](https://github.com/appsignal/appsignal-elixir/blob/b1b4c1a102c872ccf45374bcb6a69ed4c4ad4a1e/lib/appsignal.ex#L82).

It's being triggered because no AppSignal Push API key could be found, which would be the case in the test env. You can set it to any value in your test environment suppress the message.

```elixir
config :appsignal, :config,
  active: false,
  push_api_key: "foo"
```

**Comment by axelson** [comment]
I am using ExUnit. Maybe it's because I'm running in an Umbrella app. Looks like setting a bogus `push_api_key` works to suppress the message. However I do wish that `active: false` would suppress the message.

**Comment by tombruijn** [comment]
I wouldn't know about Umbrella apps. Maybe @jeffkreeftmeijer knows.
But yes, it would be nice if `active: false` it would ignore any invalid config (caused by the missing push_api_key option).
