### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by arjan** [appsignal/appsignal-elixir#34]
Let's add a benchmark to see what the overhead is of running the Appsignal integration in a typical Phoenix application.

**Comment by wesoudshoorn** [comment]
@thijsc Can you let us know what you want to do with this? A blogpost would be cool with the right angle 👍  Also, can you share the code for the benchmark somewhere so it's reproducible for others?

**Comment by thijsc** [comment]
After a few attempts I ended up taking https://github.com/jeffkreeftmeijer/appsignal-phoenix-example and using a benchmark tool:

Do a production compile and run it in production mode:

```
MIX_ENV=prod mix compile
PORT=4001 MIX_ENV=prod mix phoenix.server
```

Then add some records so the query on the homepage actually returns something. You can then benchmark using:

```
wrk -c 16 -t 16 -d 30s http://localhost:4001/users
```

By default AppSignal is on, you can turn it off by disabling it in the config and then recompiling the app. The difference between AppSignal on and off is between 1 and 2 ms on my machine.

This is of course not a fully reliable benchmark yet, we'd need to get a separate machine for the web server and the load tester and run it for longer periods of time to get reliable results. It would also be good to write a more complex load testing script that does multiple operations (posting some forms, navigating around). It'd be good to run the same benchmark in Rails.

I think this should be a documentation page and maybe also a blog post. Maybe we should close the issue here and open a new one in https://github.com/appsignal/appsignal-docs?
