### ISSUE TITLE
Ability to pattern match in order to ignore genserver events

### ISSUE THREAD

**Issue by sax** [appsignal/appsignal-elixir#372]
We're running into an issue, where we are sending a lot of appsignal noise due to the normal lifecycle of our genservers. Specifically, we have an elixir app that runs on-prem in our customer locations (using `phoenix_gen_socket_client` to connect to our main phoenix app) on devices that often go to sleep when not in use. When the devices wake up, the network stack takes a little longer to wake up and our genservers thrash until they can get a real connection. When the app finally gets internet access, it uploads a batch of errors, which we promptly ignore. We recently added `delayed_otp` to provide a backoff on reconnect attempts—this makes the appsignal noise even worse as it adds a variable integer (the lifetime of how long a genserver managed to stay alive before dying) to the event.

Because this happens in the error logger, it appears to be too low level in the stack for us to intercept before it gets caught by the appsignal `ErrorHandler`.

What I was thinking was to provide a function or a module that I'd register in the `Application` config, which if set would be used by the `ErrorHandler` to pattern match on the event somewhere within `match_event` and optionally return `:nomatch`.

Does this seem like a feature that would be merged if I issued a pull request, or is there an alternate way that I could do this with the existing library?

**Comment by jeffkreeftmeijer** [comment]
Hey Eric,

We have [an issue](https://github.com/appsignal/appsignal-elixir/issues/357) to improve our Erlang error handling on our backlog, which will make sure errors with variable integers like yours are properly grouped by converting all Erlang errors to Elixir exception structs.

We usually recommend using ignored_errors to ignore exceptions, but since your example handles erlang structs from the error logger, that won’t work for your use case.

I’ve discussed this with the team, and we’re open to adding an ability to add filters and mappers to reject or change certain errors. Your implementation probably looks a lot like something we'd like to do, but we'll have to do some research to decide how we want this to look. For example, we'd prefer to allow users to write a single filter/mapper class that does both in one go.

We'll work on #357 first, as that resolves the unfiltered errors problem you've been running into, and we'll do some more research to find out how we'd like to tackle this after. We'll keep you posted in this issue.

**Comment by sax** [comment]
This sounds great. I’m using our fork at the moment to reduce noise, so it is less pressing for us than a week ago.

Keep me in the loop as you gain clarity on what you’re looking for, and I can carve out some time to iterate on this. Or if there is a different implementation that makes this irrelevant, all the better.
