### ISSUE TITLE
Adding mix format

### ISSUE THREAD

**Issue by jvanbaarsen** [appsignal/appsignal-elixir#389]
I was checking out the project, and I noticed that it does not yet make use of Elixir formatter.

When I tried adding it and running it I noticed a ton of files changed, so before I actually submit such a PR I wanted to check in if you would be open for adding this?

The benefit is that it will make sure the code is "community standard". You can hook it up to your editor ( I have it hooked up for vim), to format the code on save. The downside is that it will have a one-off reviewing cost that can be quite high.

To add an extra layer of security, you can also add it to your CI.

In case you want to read more about it, you can do so here: https://hashrocket.com/blog/posts/format-your-elixir-code-now

Let me know if you would be interested in such a change.

**Comment by tombruijn** [comment]
Hi @jvanbaarsen !

I think @jeffkreeftmeijer is currently applying the new formatting for pieces of code that change. 
So yes, we do want to have this format applied _eventually_ for the entire project.

If @jeffkreeftmeijer is okay with it we could also run it once for the entire project at some point, but let's wait for a reply from him (some time next week).

**Comment by jeffkreeftmeijer** [comment]
Hey @jeroenvisser101! :wave:

Like Tom said, we've been formatting touched lines ever since 1.6 came out, meaning there's still a lot of lines that aren't correctly formatted. The plan was to do this gradually to not have a single big formatting commit and have a formatter check on CI once everything was properly formatted, so we make sure we don't mess up the formatting later.

That said, since there are parts of the integration that are hardly ever touched, this is taking a while. I'd say we're open to a patch like this. Any objections, @tombruijn? :)

**Comment by tombruijn** [comment]
@jeffkreeftmeijer yes, we don't currently have PRs open so it would be a good time to do this after releasing package v1.8.0. Something planned for this week. Then the master and develop branch are the same.
