### ISSUE TITLE
How to send an error that is not the result of an exception, Elixir 1.7+

### ISSUE THREAD

**Issue by CrowdHailer** [appsignal/appsignal-elixir#397]
If I want to report custom errors I was previously just using something like the following.

```elixir
  def custom_report() do
    Appsignal.send_error(%RuntimeError{}, "", System.stacktrace())
  end
```

This looks to be the recommended way to send an error from the docs. However calling `System.stacktrace` is now depreciated in the above usecase. 
What is the suggested way of reporting a custom error?

Happy to submit a PR to update the docs but not really sure what is a better way. We have some cases where we know something has gone wrong without a `try/catch` and introducing one just to pull out a stacktrace seems overkill

**Comment by jeffkreeftmeijer** [comment]
Hey @CrowdHailer! :wave:

We used to call `System.stacktrace()` when calling `Appsignal.send_error/1-7` without explicitly passing a stacktrace. Since`:erlang.get_stacktrace()` was deprecated outside of a `try`/`catch` block, we require the stack trace to be passed explicitly, or passing en empty list.

The example in the docs (`Appsignal.send_error(%RuntimeError{}, "", System.stacktrace())`) works without warnings, but only in a `try`/`catch` block. To send an error without an exception, you'll need to pass an empty list explicitly for now:

``` elixir
Appsignal.send_error(%RuntimeError{}, "", [])
```

Does that get you a step further? :)

**Comment by CrowdHailer** [comment]
OK, the stacktrace is useful even outside a try catch. however probably with enough information in the text of the second argument missing the stacktrace will not be a problem

**Comment by jeffkreeftmeijer** [comment]
You're right. However, getting the stacktrace on demand isn't something we can do outside of `try` blocks anymore in future versions of OTP. In Elixir itself, we're recommended to switch to `__STACKTRACE__`, which will raise an error if we call it outside of a `try` block. The only reason we're still using `System.stacktrace/0` is to support lower versions.

We're releasing https://github.com/appsignal/appsignal-elixir/pull/400 in the next patch release shortly, which will cause a warning when `Appsignal.send_error/1-7` is called without either a stacktrace of an empty list to make this clearer. Thanks for reporting that one!
