### ISSUE TITLE
Appsignal.Plug not overrideable

### ISSUE THREAD

**Issue by jdobrzanski** [appsignal/appsignal-elixir#463]
`Appsignal.Plug` does not allow another plug to override its call function (ie. through `defoverridable call: 2`) which is making it difficult to layer, for instance, provide a additional information to `plug_session` for inclusion in error sample data prior to `Appsignal.Plug.call`'s error handler.

Is there is specific reason that the approach recommended in https://github.com/phoenixframework/phoenix/issues/2791 was not done for `Appsignal.Plug`?

**Comment by jeffkreeftmeijer** [comment]
Hey @jdobrzanski,

Thanks for bringing this up. It looks like we've accidentally dropped the overridable Plug in a7b434c7c107a40738f4e42395e8c3a34e798739, and we haven't had requests to add it back since. I've pushed a fix in #464 to add it back. We're reviewing that now and it's planned to be included in the next minor release. If you have time, could you try the `overridable-call` branch in your app and let us know if that gets you a step further?

**Comment by jdobrzanski** [comment]
Thanks @jeffkreeftmeijer looks like this does the trick! Waiting for the next release!
