### ISSUE TITLE
Get configuration up to speed with the Ruby integration

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-elixir#49]
http://docs.appsignal.com/ruby/configuration/

**Comment by jeffkreeftmeijer** [comment]
I've compared the Elixir configuration options to the ones in Ruby, and these are my findings. @thijsc, @tombruijn am I correct that all options under the "Not implemented"-header should also be implemented for the Elixir integration? If so, I'll add issues for them before closing this.

# Not implemented
- :ca_file_path
- :enable_allocation_tracking
- :enable_frontend_error_reporting
- :enable_gc_instrumentation
- :hostname

## Ruby specific
- :instrument_net_http
- :instrument_redis
- :instrument_sequel

# Implemented differently from the Ruby integration
- :env (No automatic detection: https://github.com/appsignal/appsignal-elixir/issues/91)
- :name (No automatic detection: https://github.com/appsignal/appsignal-elixir/issues/92)
- :running_in_container (No automatic detection: https://github.com/appsignal/appsignal-elixir/issues/94)

**Comment by tombruijn** [comment]
- :ca_file_path
  - We should be able to set this. In the Ruby gem we ship [our own ca file](https://github.com/appsignal/appsignal-ruby/blob/d7f31875aaa9f4227eca46019692b4e8595b8325/resources/cacert.pem) but I don't find one in the Elixir package. If the user has SSL connection issues setting this to the host's ca path usually helps.
- :enable_allocation_tracking & :enable_gc_instrumentation
  - If we can monitor this in Elixir we should  
- :enable_frontend_error_reporting
  - Since this only works in combination with the Ruby gem currently and our next version should not rely on a gem/elixir package on the user's server I don't think this is necessary
- :hostname
  - yes

**Comment by jeffkreeftmeijer** [comment]
I creates issues for :ca_file_path (#97), :hostname (#98) and a general one about allocation tracking and GC instrumentation, for future reference. #98 is in the 1.0 milestone, the other two aren't. Closing this as we'll pick up the config changes in their respective issues.

**Comment by tombruijn** [comment]
Why not make #97 part of the 1.0 release as well?
Small change to pass it to the agent as an env var. I'm just not sure how much work it would be to pass it to a HTTP lib (if at all possible) like HTTPoison added in #81
