### ISSUE TITLE
Package size is very large

### ISSUE THREAD

**Issue by lpil** [appsignal/appsignal-elixir#531]
Hi!

We're trying to shrink some Elixir docker images and we're finding that the appsignal package is a large proportion of the compiled images that have it.

```
   14.9 MiB [##########] /appsignal-1.11.1
    4.3 MiB [##        ] /elixir-1.9.2
    3.9 MiB [##        ] /stdlib-3.10
    3.8 MiB [##        ] /tzdata-1.0.2
    2.3 MiB [#         ] /waive-1.0.0
    2.2 MiB [#         ] /timex-3.6.1
    1.9 MiB [#         ] /compiler-7.4.6
    1.8 MiB [#         ] /kernel-6.5
    1.6 MiB [#         ] /comeonin-5.1.2
    1.5 MiB [          ] /crypto-4.6
    1.4 MiB [          ] /ssl-9.4
    1.1 MiB [          ] /ecto-3.2.3
    1.1 MiB [          ] /phoenix-1.4.10
    1.0 MiB [          ] /jose-1.9.0
    1.0 MiB [          ] /mix-1.9.2
... more
```

Most of the data is these files

```
    6.8 MiB [##########]  libappsignal.a
    4.7 MiB [######    ]  appsignal-agent
    2.8 MiB [####      ]  appsignal_extension.so
```

Would it be possible to build these artefacts to be smaller? Strip any debug information for example.

Thank you,
Louis

**Comment by jeffkreeftmeijer** [comment]
Hey @lpil,

Thanks for raising this issue. The build shouldn't include debug information in the current version. We've done some testing to see if you could easily remove the `libappsignal.a` file after compiling the extension. However, that causes trouble recompiling the extension if that's ever needed, which would require updating the dependency to get a new version of the file. Because of that, we haven't added removing the `.a` file to our Makefile.

We'll keep this issue open to stay the lookout for ways to reduce the package size. Any suggestions here would be welcome. :)

**Comment by lpil** [comment]
Thank you. Merry Christmas to all at AppSignal! 🎄
