### ISSUE TITLE
Compilation often fails the on a clean build

### ISSUE THREAD

**Issue by axelson** [appsignal/appsignal-elixir#584]
## Describe the bug

When running `rm -rf _build` and then `mix compile` I often get this compilation error:
```
==> appsignal
AppSignal extension installation successful
Compiling 48 files (.ex)

== Compilation error in file lib/appsignal/diagnose/library.ex ==
** (UndefinedFunctionError) function Appsignal.Nif.agent_version/0 is undefined (module Appsignal.Nif is not available)
    Appsignal.Nif.agent_version()
    lib/appsignal/diagnose/library.ex:3: (module)
    (stdlib 3.13) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.11.0) lib/kernel/parallel_compiler.ex:314: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7

15:01:05.522 [error] Process #PID<0.9038.0> raised an exception
** (ArgumentError) argument error
    :erlang.load_nif(:erlang, :apply)
    lib/appsignal/nif.ex:41: Appsignal.Nif.init/0
    (kernel 7.0) code_server.erl:1355: anonymous fn/1 in :code_server.handle_on_load/5

15:01:05.526 [warn]  The on_load function for module Elixir.Appsignal.Nif returned:
{:badarg,
 [
   {:erlang, :load_nif, [:erlang, :apply], []},
   {Appsignal.Nif, :init, 0, [file: 'lib/appsignal/nif.ex', line: 41]},
   {:code_server, :"-handle_on_load/5-fun-0-", 1,
    [file: 'code_server.erl', ...]}
 ]}

could not compile dependency :appsignal, "mix compile" failed. You can recompile this dependency with "mix deps.compile appsignal", update it with "mix deps.update appsignal" or clean it with "mix deps.clean appsignal"
```

## To Reproduce

- Using AppSignal for Elixir package version 1.13.4
- `rm -rf _build`
- `mix compile`

**Comment by jeffkreeftmeijer** [comment]
Am I correct you're running OTP 23.0.0, 23.0.1 or 23.0.2? It looks like you're running into [ERL-1273](https://bugs.erlang.org/projects/ERL/issues/ERL-1273?filter=allissues), which was fixed in OTP 23.0.3 back in July, so updating to a newer version of OTP 23 would do the trick. 

However, another issue we've seen is that the bitwalker/alpine-elixir-phoenix Docker image depends on bitwalker/alpine-elixir-erlang, which is locked on OTP 23.0.2. There are [pull requests open to bump the version](https://github.com/bitwalker/alpine-erlang/pulls), but no new version has been released yet. Am I also correct you're running this in Docker, on the bitwalker images?

I've gone ahead and forked alpine-elixir-phoenix, alpine-elixir and alpine-erlang, and I've bumped the Erlang version in the latter to 23.0.3. Using this string of images fixes the issue for me.
If my assumptions about you using that bitwalker image are correct, could you try running on my images by switching from bitwalker/alpine-elixir-phoenix:latest to `jkreeftmeijer/alpine-elixir-phoenix:latest, to see if that resolves the issue for you too?

**Comment by axelson** [comment]
You're correct on the first bit, I was running 23.0.2, and indeed it does look like ERL-1273 is the cause of my problem. I'm upgrading to 23.0.4 right now and will report back once I have a chance to check. (I did just try 23.1.1 but I'm getting some weird errors on it). Unfortunately I don't have docker on this machine so I can't help with testing that image.

**Comment by axelson** [comment]
Since I'm having so much trouble installing a newer version to check, I'm going to close this issue. If I can reproduce it on newer version of OTP then I'll re-open it, but I'm pretty confident that I won't be able to. Thanks for the info!

**Comment by jeffkreeftmeijer** [comment]
Hey @axelson,

Great! No need to test that Docker image, that was just a guess on my side. Please do let us know if upgrading doesn't resolve this. :)
