### ISSUE TITLE
No obvious replacement for `Appsignal.Transaction.set_action/1` in version 2.0.0

### ISSUE THREAD

**Issue by kenny-evitt** [appsignal/appsignal-elixir#587]
The relevant code:

```elixir
    Appsignal.Transaction.set_action("GET #{path}")
```

`mix compile` warning:

```
warning: Appsignal.Transaction.set_action/1 is undefined (module Appsignal.Transaction is not available or is yet to be defined)
```

The 'upgrading from 1.x to 2.x' doc doesn't mention what needs to be changed for this:

- [Upgrading from Appsignal for Elixir 1.x to 2.x | AppSignal documentation](https://docs.appsignal.com/elixir/installation/upgrading-from-1.x-to-2.x.html)

The Hex docs mention that all of the functions in `Appsignal.Transaction` (except `generate_id/0`) have been deprecated and the deprecation notice for `set_action/1` do point to another module:

> This function is deprecated. Use `Appsignal.Span` instead..

But there's no `set_action/1` function in [`Appsignal.Span`](https://hexdocs.pm/appsignal/Appsignal.Span.html#content).

Any advice?

**Comment by jeffkreeftmeijer** [comment]
Hey @kenny-evitt,

Thanks for letting us know about this. We'll be sure to update the documentation, because this is a bit of a pitfall, indeed.

For Plug or Phoenix apps, we've added `Appsignal.Plug.put_name/2`, which adds the new name to the conn. You'll have to make sure you call `put_name/2` on the conn that's returned in the action.

``` elixir
defmodule AppsignalPlugExample do
  use Plug.Router
  use Appsignal.Plug
  plug(:match)
  plug(:dispatch)

  get "/" do
    conn
    |> Appsignal.Plug.put_name("AppsignalPlugExample#index")
    |> send_resp(200, "Welcome")
  end
end
```

Does that get you a step further? I'll work on that documentation page, and I'll update you here when that's live.

**Comment by kenny-evitt** [comment]
@jeffkreeftmeijer This seems to work! Thanks!

The 2.0.0 version also seems to fix #319.

**Comment by jeffkreeftmeijer** [comment]
Awesome, thanks for getting back to me on this. Great to hear this also solved the issue in #319 for you, we split the libraries up to make sure we won't run into optional compilation issues like that again. I'll be sure to update that issue. 

Oh, and I've just merged the documentation update. Thanks again!

**Comment by kenny-evitt** [comment]
@jeffkreeftmeijer You're welcome! Thanks for your help!

**Comment by iv-mexx** [comment]
Hi @jeffkreeftmeijer I have the same question for Channels when using the `channel_action` Decorator

```
  @decorate channel_action()
  def join(@topic <> group, params, socket) do
    Appsignal.Transaction.set_action("GroupChannel#join")
    ...
  end
```

**Comment by jeffkreeftmeijer** [comment]
Hey @iv-mexx,

Since you don’t have a conn there, you should be able to [set the action name direcly on the current Span](https://docs.appsignal.com/elixir/installation/upgrading-from-1.x-to-2.x.html#custom-instrumentation): 

```
Appsignal.Span.set_name(Appsignal.Tracer.current_span(), "AppsignalElixirExample#index”)
```

In your case, your function would look something like this:

``` elixir
decorate channel_action()
  def join(@topic <> group, params, socket) do
    Appsignal.Span.set_name(Appsignal.Tracer.current_span(), "GroupChannel#join")   
     ...
  end
```

Could you try that and open a new issue if you run into any issues?

**Comment by iv-mexx** [comment]
Looking good, thanks!
