### ISSUE TITLE
Call.Phoenix event spans the full request

### ISSUE THREAD

**Issue by JMurphyWeb** [appsignal/appsignal-elixir#604]
<img width="893" alt="Screenshot 2020-12-11 at 13 13 39" src="https://user-images.githubusercontent.com/12638261/101902839-9a5e7b00-3bb3-11eb-82ae-2b7e1dcbe9e6.png">
<img width="901" alt="Screenshot 2020-12-11 at 13 13 31" src="https://user-images.githubusercontent.com/12638261/101902850-9d596b80-3bb3-11eb-8cfc-523202506f26.png">

## Describe the bug

See screenshots.

Since upgrade to 2.0, I have Call.Phoenix event spanning the full request. Is that intentional?

## To Reproduce

I occurs in every route for the performance tab

**Comment by jeffkreeftmeijer** [comment]
Hey @JMurphyWeb,

That’s correct. Our [plug integration](https://github.com/appsignal/appsignal-elixir-plug/blob/main/lib/appsignal_plug.ex) wraps the request handled by Phoenix with a call.phoenix event to mark where Phoenix app takes over. This means that whatever happens within the request is placed inside that wrapper event.

It was added in 2.0, and it’s intentional, indeed. :)
