### ISSUE TITLE
Support logging to the log file

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-elixir#747]
The Elixir integration appears to have a logger that only logs to STDOUT. It should log to the configured file location if the `log` option is configured to `file` (which is the default).

See also the reference of how logging should work in the integrations https://github.com/appsignal/integration-guide/blob/main/build/logging.md (private link).

## To do

- [ ] The Logger should be configured to use the `Config.log_file_path()` location if `log: file`.
- [ ] The Logger should be configured to log to STDOUT if `log: stdout`.

**Comment by unflxw** [comment]
Still working on this. I've talked about this on Slack, but here's a compiled update on my progress on this task so far. First, some observations on the starting point for this task:

- While a centralised logger does exist (`Appsignal.Logger`), it is mostly unused. Most of our log statements use Elixir's `Logger` directly.
- The centralised logger does not currently meet the specification for the logger in the integration guide. The formatting of the messages does not match, it does not support log levels other than "debug", and it has no way to send specific messages to standard error.
- As it currently exists, the centralised logger is itself a thin wrapper around Elixir's `Logger`, which is configured globally, at the application level. Any changes to its configuration, such as setting the log level threshold, adding a backend that writes to a file, or changing the formatting of the logs to match the integration guide, would apply to all logs emitted by the application, not just those emitted by the integration.

Based on this, the following goals are added:

- For this task to make sense in practice, the centralised logger should be used whenever possible. No point in having a logger that writes to a file if it's not used most of the time.
- If we're going to be writing to the log file that is shared with the extension and the agent, the formatting should match the one used by the extension and the agent, which is the one described in the integration guide.

To meet these goals, I first implemented a logger that complies with the specification. This logger was implemented as a GenServer, since it kept some information (its log level threshold and the log file handle) as state. As it turns out, most of our logging messages are emitted when the application is booting up, before the logger can be assumed to be ready. This meant that, in practice, the logger couldn't be used for most of our needs.

I have now reworked that logger to make it not be a GenServer, which makes it possible to use it at any point in the application's lifecycle. I'm now working on making sure it's used wherever possible.

The Config module in particular will require some small changes to be able to use it, as some configuration values must be computed, and can emit logging messages if they're deprecated. Among those computed values is the path to the log file, which is required by the logger, resulting in a circular dependence of sorts.
