### ISSUE TITLE
Fix dialyzer warnings on Elixir 1.15

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-elixir#853]
The new dialyzer warnings show an issue in the return types of the Nif's diagnose function that can never be reached. 

https://github.com/appsignal/appsignal-elixir/pull/851/commits/20a7abbd8f1358beada39192a3ec1ad70c47675d ignores these errors for now in order to fix the build and ship the changes needed to run CI on Elixir 1.15, but these should be looked into.

**Comment by tombruijn** [comment]
I had a brief look. This seems to be an issue because it doesn't know the Nif replaces the Nif module's `_diagnose` function when it's loaded. So it thinks it can only ever return `:error` and as such never go through the happy path and decode the agent's JSON diagnose report.

Can we tell dialyzer that it can return something else when the Nif is loaded?
