### ISSUE TITLE
(Mox) testing guidelines?

### ISSUE THREAD

**Issue by thbar** [appsignal/appsignal-elixir#889]
I am going to implement a bit of tests for a Ecto handler triggering AppSignal custom metrics.

For some context, see:
- https://github.com/appsignal/appsignal-elixir/issues/318#issuecomment-841156779 (which I'm basing my implementation on)
- https://github.com/appsignal/appsignal-elixir/issues/887

I would like to add a bit of tests specifically on that handler, and a bit of Mox'ing around `AppSignal`.

The thing is unless I missed it, I do not see `@behaviour`/`@callback` in `AppSignal` which would let Mox work here.

I could create a small wrapper around the functions I'm interested in, like:

https://github.com/appsignal/appsignal-elixir/blob/34e6751afb0f44b81ab19d589fef11bd266903fe/lib/appsignal.ex#L145-L151

but I wonder if there is some testing facility that could help here.

Typically, I would attach, during the test, the handler via a unique handler id like done here:

https://github.com/dashbitco/broadway/blob/main/test/broadway_test.exs#L311-L318

and would issue a couple of calls on Ecto (working in a sandbox), and assert that `AppSignal` has received the right calls (in that case the SUT or System Under Test would be the telemetry handler module I'm writing).

Of course in the example described in https://github.com/appsignal/appsignal-elixir/issues/318#issuecomment-841156779, there is no big risk to ship this, but as we add more (varied) custom metrics, it will be beneficial to be able to implement such tests, in particular to catch integration troubles on package upgrades, for instance.

Are there some guidelines on how to test around AppSignal?

Should I just create a small wrapper with the same typespec & Mox that, since we control it, or is there something better?

Thanks!

**Comment by unflxw** [comment]
Hi @thbar!

I am not very familiar with Mox, so my answer here may miss the mark.

Internally, to test AppSignal, we make it so that [modules reference other modules via attributes](https://github.com/appsignal/appsignal-elixir/blob/34e6751afb0f44b81ab19d589fef11bd266903fe/lib/appsignal/oban.ex#L6), the values for which are obtained from our configuration. Then we [implement fake modules that provide the same API](https://github.com/appsignal/appsignal-elixir/blob/34e6751afb0f44b81ab19d589fef11bd266903fe/test/support/appsignal/fake_appsignal.ex), and [our test environment configuration loads those fake modules](https://github.com/appsignal/appsignal-elixir/blob/34e6751afb0f44b81ab19d589fef11bd266903fe/config/config.exs#L7), which store the values that they receive when called, so that [our tests can make assertions against those](https://github.com/appsignal/appsignal-elixir/blob/34e6751afb0f44b81ab19d589fef11bd266903fe/test/appsignal/oban_test.exs#L119-L123).

This seems very similar to what Mox does, going by [their documentation](https://hexdocs.pm/mox/Mox.html) -- the big difference, of course, being that Mox creates the fake modules automatically for you.

So, yes, you could create a thin wrapper around AppSignal that defines attributes for methods in the way that Mox expects, then ask Mox to create a mock for it. If you're already using Mox throughout your test suite, this is probably the solution that is more in sync with how your test suite already handles these problems.

But you could also use our `FakeAppsignal` module, or create your own without Mox -- though do keep in mind that we don't consider the fake module itself part of our public-facing API, and we might change it at any time for any reason (but we probably won't)

**Comment by unflxw** [comment]
No problem at all! Thank you for always asking such thoughtful questions 👍
